### ISSUE TITLE
Setting hairStyle to "mohawk" or "thick" resets the hairColor to black

### ISSUE THREAD

**Issue by itskaustubh** [chilllab/react-nice-avatar#16]
Any particular reason why the mohawk.js and thick.js  in src/hair has code :
`mainColor = colorRandom && color || "#171921";` ?

All the other styles just have: `const { color } = props;` 
The other styles work fine.
'mohawk' and 'thick' seem to reset the haircolor to 'black' or #171921 in my project.

Also, the demo on https://nice-avatar.chilllab.io/ works fine. 
What react-nice-avatar version is the demo running?

**Comment by wwayne** [comment]
@itskaustubh You can add `hairColorRandom: true` to your config or props so that those 2 hairstyles won't be forced reset.
<img width="899" alt="截屏2021-06-15 下午12 20 50" src="https://user-images.githubusercontent.com/5305874/121992441-3ae85e80-cdd4-11eb-915d-f79266d22f24.png">

The demo is using `hairColorRandom: true` so you can see colorful hair, but the default is false

**Comment by itskaustubh** [comment]
@wwayne It works perfect! Thanks Wayne. You can close this one.
Quick Question.. How do I access Eyebrow styles.. Is that still in the works?

**Comment by wwayne** [comment]
@itskaustubh I didn't make it accessible because I feel the random color/style of the eyebrow looks weird in most cases, so I make it `private` intended
